baseDomain: 127.0.0.1.nip.io

replicaCount:
  vueFe: 1
  springbootBe: 1
  fastapiBe: 1

imagePullSecrets: []
# imagePullSecrets:
#   - name: dockerhub-regcred

images:
  vueFe:
    repository: docker.io/gjaku1031/ken-ssafy
    tag: vue-fe-70f8396c
    pullPolicy: IfNotPresent
  springbootBe:
    repository: docker.io/gjaku1031/ken-ssafy
    tag: springboot-be-70f8396c
    pullPolicy: IfNotPresent
  fastapiBe:
    repository: docker.io/gjaku1031/ken-ssafy
    tag: fastapi-be-70f8396c
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: traefik
