server:
  port: 8080
  forward-headers-strategy: framework

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:./springboot-be/.env[.properties]
      - optional:file:./a506/springboot-be/.env[.properties]
      - optional:file:./../a506/springboot-be/.env[.properties]
  application:
    name: springboot-be
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      database: ${SPRING_DATA_REDIS_DATABASE}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

app:
  cors:
    allowed-origin-patterns: ${APP_CORS_ALLOWED_ORIGIN_PATTERNS}
  fastapi:
    base-url: ${APP_FASTAPI_BASE_URL}
