{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.clusterIssuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer | quote }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - kairos.{{ .Values.baseDomain }}
        - spring.{{ .Values.baseDomain }}
  {{- end }}
  rules:
    - host: kairos.{{ .Values.baseDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vue-fe
                port:
                  number: 80
    - host: spring.{{ .Values.baseDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-be
                port:
                  number: 8080
{{- end }}
